### ISSUE TITLE
Settings wont be saved?

### ISSUE THREAD

**Issue by xeonixo** [akaunting/docker#105]
Hi! I am new to Akaunting, i wanted to change from ODOO.

Installing was a bit unusual and not really easy.

Got it multiple times to the same result:

Settings from my company will not be saved... settings in my profile however are saved (changed email, password)

I cannot add a phone number, cannot change the date format and nearly everything else, after save and page reload the values are gone.

Is there an issue due to the locale de-DE?

My Docker Compose:
```
  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:latest
    build:
      context: .
    volumes:
      - akaunting:/var/www/html
    restart: unless-stopped
    env_file:
      - akaunting/docker/env/run.env
    environment:
    #  - AKAUNTING_SETUP=true
      - APP_DEBUG=true
    depends_on:
      - sql
    networks:
      heimnetz:
        ipv4_address: 192.168.0.130
```

My run.env:
```
# You should change this to match your reverse proxy protocol, DNS name and port (if non standard port is used)
APP_URL=https://akaunting. (does not matter)
LOCALE=de-DE
# Don't change this unless you rename your database container or use rootless podman, in case of using rootless podman you should set it to 127.0.0.1 (NOT localhost)
DB_HOST=192.168.0.129
DB_PORT=3306
# Change these to match env/db.env
DB_NAME=akaunting
DB_USERNAME=akaunting
DB_PASSWORD=(does not matter)
# You should change this to a random string of three numbers or letters followed by an underscore
DB_PREFIX=asd_
# These define the first company to exist on this instance. They are only used during setup.
COMPANY_NAME=(does not matter)
COMPANY_EMAIL=(does not matter)

# This will be the first administrative user created on setup.
ADMIN_EMAIL=(does not matter)
ADMIN_PASSWORD=(does not matter)

```
