### ISSUE TITLE
Can't use bind volumes

### ISSUE THREAD

**Issue by Tiritibambix** [akaunting/docker#114]
After having the same issue as #111 , I tried using only docker volumes and it worked.

I would like to be able to use volumes like this:
```
version: '3.7'

services:

  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:latest
    build:
      context: .
    ports:
      - 1261:80
    volumes:
      - /PATH/TO/PERSISTENT/DATA/ON/MY/DRIVE/akaunting-data:/var/www/html
    restart: unless-stopped
    env_file:
      - env/run.env
    environment:
      - AKAUNTING_SETUP
    depends_on:
      - akaunting-db

  akaunting-db:
    container_name: akaunting-db
    image: mariadb
    volumes:
      - /PATH/TO/PERSISTENT/DATA/ON/MY/DRIVE/akaunting-db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - env/db.env

#volumes:
#  akaunting-data:
#  akaunting-db:
```

How can I achieve that @MohammedAl-Mahdawi  ?
Thanks for your help.
