### ISSUE TITLE
Akaunting Not Working with Docker Compose (Resolved – See Solution)

### ISSUE THREAD

**Issue by adnanjaw** [akaunting/docker#118]
I have this docker compose file. i'm trying to run Akaunting using docker image from `akaunting/akaunting:latest` i keep getting

```bash
akaunting-1     | 2025-02-06T16:57:48.324532737Z 2025-02-06 16:57:48+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.4-1.el9 started.
akaunting-1     | 2025-02-06T16:57:48.562989502Z 2025-02-06 16:57:48+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
akaunting-1     | 2025-02-06T16:57:48.573791490Z 2025-02-06 16:57:48+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.4-1.el9 started.
akaunting-1     | 2025-02-06T16:57:48.795071442Z 2025-02-06 16:57:48+00:00 [ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
akaunting-1     | 2025-02-06T16:57:48.795096469Z     You need to specify one of the following as an environment variable:
akaunting-1     | 2025-02-06T16:57:48.795099785Z     - MYSQL_ROOT_PASSWORD
akaunting-1     | 2025-02-06T16:57:48.795102651Z     - MYSQL_ALLOW_EMPTY_PASSWORD
akaunting-1     | 2025-02-06T16:57:48.795105486Z     - MYSQL_RANDOM_ROOT_PASSWORD
```

this is docker compose:

```yml
name: akaunting

services:
  akaunting:
    image: akaunting/akaunting:latest
    depends_on:
      - akaunting-db
    restart: unless-stopped
    environment:
      AKAUNTING_SETUP: true
      APP_URL: https://${AKAUNTING_APP_DOMAIN}
      APP_LOCALE: en-US
      APP_secret: base64:ZKnd6vnK/u6pMm5MoQOZ+o6om1jCYVf3v5QHj8pf2sY=
      COMPANY_NAME: company
      COMPANY_EMAIL: info@company.nl
      ADMIN_EMAIL: info@company.nl
      ADMIN_PASSWORD: password
      DB_CONNECTION: mysql
      DB_HOST: akaunting-db
      DB_PORT: 3306
      DB_DATABASE: akaunting_db
      DB_USERNAME: akaunting_user
      DB_PASSWORD: your_secure_password
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.akaunting.service: akaunting
      traefik.http.routers.akaunting.rule: Host(`${AKAUNTING_APP_DOMAIN}`)
      traefik.http.routers.akaunting.entrypoints: https
      traefik.http.services.akaunting.loadbalancer.server.port: 80
      traefik.http.routers.akaunting.tls: true
      traefik.http.routers.akaunting.tls.certresolver: ${TRAEFIK_CERT_RESOLVER}
    volumes:
      - akaunting-data:/var/www/html
    networks:
      - akaunting
      - proxy

  akaunting-db:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYSQL_IMAGE_VERSION: ${AKAUNTING_MYSQL_IMAGE_VERSION}
    cap_add:
      - SYS_NICE
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: "50m"
        max-file: "5"
    ports:
      - "3337:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: akaunting_db
      MYSQL_USER: akaunting_user
      MYSQL_PASSWORD: your_secure_password
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - akaunting-db:/var/lib/mysql
      - akaunting-db-log:/var/log/mysql
    networks:
      - akaunting

networks:
  akaunting:
    driver: bridge
  proxy:
    external: true

volumes:
  akaunting-data:
  akaunting-db-log:
    driver: local
  akaunting-db:
    name: akaunting-db
    driver: local
```

Thank you

**Comment by adnanjaw** [comment]
after adding `MYSQL_ROOT_PASSWORD` to `akaunting`  i get 
```bash

akaunting-db-1  | 2025-02-06T17:00:13.710094692Z 2025-02-06 17:00:13+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.4-1.el9 started.
akaunting-db-1  | 2025-02-06T17:00:13.972549525Z 2025-02-06 17:00:13+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
akaunting-db-1  | 2025-02-06T17:00:13.981811811Z 2025-02-06 17:00:13+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.4-1.el9 started.
akaunting-db-1  | 2025-02-06T17:00:14.223193477Z 2025-02-06 17:00:14+00:00 [Note] [Entrypoint]: Initializing database files
akaunting-1     | 2025-02-06T17:00:14.051408094Z 2025-02-06 17:00:14+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.4-1.el9 started.
akaunting-1     | 2025-02-06T17:00:14.308877097Z 2025-02-06 17:00:14+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
akaunting-1     | 2025-02-06T17:00:14.317433282Z 2025-02-06 17:00:14+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.4-1.el9 started.
akaunting-1     | 2025-02-06T17:00:14.545731111Z 2025-02-06 17:00:14+00:00 [Note] [Entrypoint]: Initializing database files
akaunting-1     | 2025-02-06T17:00:17.750212002Z 2025-02-06 17:00:17+00:00 [Note] [Entrypoint]: Database files initialized
akaunting-1     | 2025-02-06T17:00:17.753057722Z 2025-02-06 17:00:17+00:00 [Note] [Entrypoint]: Starting temporary server
akaunting-db-1  | 2025-02-06T17:00:18.406656694Z 2025-02-06 17:00:18+00:00 [Note] [Entrypoint]: Database files initialized
akaunting-db-1  | 2025-02-06T17:00:18.408370006Z 2025-02-06 17:00:18+00:00 [Note] [Entrypoint]: Starting temporary server
akaunting-1     | 2025-02-06T17:00:18.437364184Z 2025-02-06 17:00:18+00:00 [Note] [Entrypoint]: Temporary server started.
akaunting-1     | 2025-02-06T17:00:18.465364987Z '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
akaunting-1     | 2025-02-06T17:00:18.880979290Z Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
akaunting-1     | 2025-02-06T17:00:18.881004217Z Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
akaunting-1     | 2025-02-06T17:00:18.881006631Z Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
akaunting-db-1  | 2025-02-06T17:00:19.204551286Z 2025-02-06 17:00:19+00:00 [Note] [Entrypoint]: Temporary server started.
akaunting-db-1  | 2025-02-06T17:00:19.230701137Z '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
akaunting-db-1  | 2025-02-06T17:00:19.683904527Z Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
akaunting-db-1  | 2025-02-06T17:00:19.683927942Z Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
akaunting-db-1  | 2025-02-06T17:00:19.683930457Z Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
akaunting-1     | 2025-02-06T17:00:19.689512399Z Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
akaunting-1     | 2025-02-06T17:00:19.689546924Z Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
akaunting-1     | 2025-02-06T17:00:19.689549609Z Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
akaunting-1     | 2025-02-06T17:00:19.779002842Z 
akaunting-1     | 2025-02-06T17:00:19.780995393Z 2025-02-06 17:00:19+00:00 [Note] [Entrypoint]: Stopping temporary server
akaunting-db-1  | 2025-02-06T17:00:20.435337145Z Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
akaunting-db-1  | 2025-02-06T17:00:20.435356021Z Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
akaunting-db-1  | 2025-02-06T17:00:20.435358345Z Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
akaunting-db-1  | 2025-02-06T17:00:20.517265840Z 2025-02-06 17:00:20+00:00 [Note] [Entrypoint]: Creating database akaunting_db
akaunting-db-1  | 2025-02-06T17:00:20.533645180Z 2025-02-06 17:00:20+00:00 [Note] [Entrypoint]: Creating user akaunting_user
akaunting-db-1  | 2025-02-06T17:00:20.552247549Z 2025-02-06 17:00:20+00:00 [Note] [Entrypoint]: Giving user akaunting_user access to schema akaunting_db
akaunting-db-1  | 2025-02-06T17:00:20.562907087Z 
akaunting-db-1  | 2025-02-06T17:00:20.564868579Z 2025-02-06 17:00:20+00:00 [Note] [Entrypoint]: Stopping temporary server
akaunting-db-1  | 2025-02-06T17:00:21.574107469Z 2025-02-06 17:00:21+00:00 [Note] [Entrypoint]: Temporary server stopped
akaunting-db-1  | 2025-02-06T17:00:21.574141563Z 
akaunting-db-1  | 2025-02-06T17:00:21.577158298Z 2025-02-06 17:00:21+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
akaunting-db-1  | 2025-02-06T17:00:21.577189216Z 
akaunting-1     | 2025-02-06T17:00:21.793726919Z 2025-02-06 17:00:21+00:00 [Note] [Entrypoint]: Temporary server stopped
akaunting-1     | 2025-02-06T17:00:21.793755133Z 
akaunting-1     | 2025-02-06T17:00:21.796343134Z 2025-02-06 17:00:21+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
akaunting-1     | 2025-02-06T17:00:21.796384693Z 

```

**Comment by jmullings** [comment]
Below is s automated solution. In this example the Dockerfile does all the extra configuration (installing sudo, creating the needed directory and appending the ServerName directive) so that when the container starts Apache it already uses the proper settings. The build script then removes any old container, builds the image, and runs a new container mapping host port 8080 to the container’s Apache port. (If your base image already uses port 8080, simply adjust the published ports accordingly.) 

─────────────────────────────  
File: Dockerfile
─────────────────────────────  
FROM akaunting/akaunting:latest

# Install sudo (if needed)
RUN apt-get update && apt-get install -y sudo

# Ensure the directory exists and set proper permissions
RUN mkdir -p /root/akaunting && chown -R 2000:2000 /root/akaunting

# Add ServerName directive to Apache configuration
RUN echo 'ServerName localhost' >> /etc/apache2/apache2.conf

# Expose the Apache port (by default Apache uses 80)
EXPOSE 80

# (The base image should supply the CMD to start Apache.)
  
─────────────────────────────  
File: build.sh
─────────────────────────────  
#!/bin/bash
set -e

# Define names for easier reuse
CONTAINER_NAME="akaunting"
IMAGE_NAME="bnb-akaunting-docker"

# Remove any existing container with the same name
if [ "$(docker ps -aq -f name=${CONTAINER_NAME})" ]; then
    echo "Stopping and removing existing container: ${CONTAINER_NAME}"
    docker rm -f ${CONTAINER_NAME}
fi

# Build the Docker image (the Dockerfile in the current directory is used)
echo "Building Docker image ${IMAGE_NAME}..."
docker build -t ${IMAGE_NAME} .

# Run the container, mapping host port 8080 to container port 80
echo "Running container ${CONTAINER_NAME}..."
docker run -d --name ${CONTAINER_NAME} -p 8080:80 ${IMAGE_NAME}

echo "Akaunting application is up and running at http://localhost:8080"
─────────────────────────────  

Usage:
1. Make sure both files are in your working directory.
2. Give execute permission to the build script (if not already):
   chmod +x build.sh
3. Run the build script:
   ./build.sh

This solution automatically builds the Docker image, removes any previous instance of the container, and launches a new container with the desired configuration and port mapping. Adjust any additional settings (such as port numbers or file locations) as needed for your environment.

**Comment by adnanjaw** [comment]
### My solution

1) The `phpfpm` (Akaunting) container is running as `user: root`. This isn't best practice, but it was necessary to avoid permission issues when mounting `/var/www/html` as a volume.  
   - If using a bind mount (a local path on the host), running as root might not be needed.  
2) `AKAUNTING_SETUP: true` is set because it handles database setup and migrations.  

3) The NGINX config and **templates** are from [[Akaunting’s official Docker repo](https://github.com/akaunting/docker/blob/master/nginx)](https://github.com/akaunting/docker/blob/master/nginx).**

### docker-compose.ym;

```yml
x-restart-always: &restart-always
  restart: always

services:
  phpfpm:
    image: akaunting/akaunting:3-fpm
    user: root
    environment:
      AKAUNTING_SETUP: true
      APP_URL: https://${APP_DOMAIN:-webapp.local}
      LOCALE: nl-NL
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DATABASE_NAME:-akaunting}
      DB_USERNAME: ${DATABASE_USER:-admin}
      DB_PASSWORD: ${DATABASE_PASSWORD:-akaunting_password}
      DB_PREFIX: asd_
      COMPANY_NAME: My Company
      COMPANY_EMAIL: my@company.com
      ADMIN_EMAIL: me@company.com
      ADMIN_PASSWORD: password
    volumes:
      - akaunting-data:/var/www/html
    networks:
      - webapp

  nginx:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
      args:
        NGINX_IMAGE_VERSION: ${NGINX_IMAGE_VERSION}
    security_opt:
      - no-new-privileges:true
    <<: [*restart-always]
    volumes:
      - akaunting-data:/var/www/html
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.webapp-nginx.priority: 100
      traefik.http.routers.webapp-nginx.tls: true
      traefik.http.routers.webapp-nginx.entrypoints: websecure
      traefik.http.routers.webapp-nginx.rule: Host(`${APP_DOMAIN:-webapp.local}`)
      traefik.http.routers.webapp-nginx.service: webapp-nginx
      traefik.http.services.webapp-nginx.loadbalancer.server.port: 80
    networks:
      - webapp
      - proxy

  mysql:
    build:
      context: .docker/mysql
      dockerfile: Dockerfile
      args:
        MYSQL_IMAGE_VERSION: ${MYSQL_IMAGE_VERSION}
    cap_add:
      - SYS_NICE
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: "50m"
        max-file: "5"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    <<: [*restart-always]
    environment:
      MYSQL_USER: ${DATABASE_USER:-admin}
      MYSQL_DATABASE: ${DATABASE_NAME:-akaunting}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-password}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-akaunting_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_log:/var/log/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - webapp

  wait:
    image: waisbrot/wait
    environment:
      TARGETS: mysql:3306 nginx:80
      TIMEOUT: 300
    networks:
      - webapp

volumes:
  mysql_data:
    driver: local
  mysql_log:
    driver: local
  akaunting-data:
    driver: local

networks:
  webapp:
    driver: bridge
  proxy:
    external: true
```

### Nginx config
https://github.com/akaunting/docker/blob/master/nginx/templates/default.conf.template

### MySql version 8.4

`.docker/mysql/config`

```conf
[mysqld]
; The default_authentication_plugin=caching_sha2_password is default in 8.4 and should be removed
character_set_server=utf8mb4
collation_server=utf8mb4_0900_as_cs
innodb_lock_wait_timeout=60
innodb_rollback_on_timeout=ON
innodb_buffer_pool_size=1024M
sort_buffer_size=1024K
max_connections=15
max_allowed_packet=128M
performance_schema=OFF
log_bin=ON
binlog_expire_logs_seconds=864000
log_output=FILE
general_log=1
general_log_file=/var/log/mysql/mysql.log
log_error=/var/log/mysql/error.log
slow_query_log=1
slow_query_log_file=/var/log/mysql/mysql-slow.log
long_query_time=1
log_queries_not_using_indexes=ON
log_slow_admin_statements=ON
```
