### ISSUE TITLE
Upgrading container from 2.1.35 to 3.0.0 returns 500 Error

### ISSUE THREAD

**Issue by NajibNour** [akaunting/docker#88]
Good day, 

Hope all is well.
Here's a couple of config files I've got to get a base line.
Docker-compose:
```
version: '2'

services:

  akaunting:
    image: docker.io/akaunting/akaunting:2.1.33
    #image: 13c16f1c3ff2
    build:
      context: .
    ports:
      - 8090:80
    volumes:
      - /srv/Docker-Volumes/Akaunting/akaunting-data/:/var/www/html/storage
      - /srv/Docker-Volumes/Akaunting/akaunting-modules/:/var/www/html/modules
    restart: unless-stopped
    env_file:
      - ./env/run.env
        #environment:
        #- AKAUNTING_SETUP
    depends_on:
      - akaunting-db

  akaunting-db:
    image: linuxserver/mariadb:latest
    volumes:
      - /srv/Docker-Volumes/Akaunting/akaunting-db/:/config
    restart: unless-stopped
    env_file:
      - ./env/db.env

networks:
  default:
    external:
      name: nginxproxymanager_default 
```

Starting on container ``akaunting:2.1.33``  When upgrading akaunting within the GUI it upgrades to 2.1.36. Im assuming it passes to 2.1.36 as it shows up in the bottom corner but then gives an error stating **You can not upgrade to Akaunting 3.0 version because your PHP version is lower than 8.0.2. Please, ask your hosting company to upgrade your PHP.**

Understandable, so then I proceed in searching for the newest image with php8 installed. So that comes up to ``akaunting:3.0.0``.

Upgrade to 3.0.0 container, I then get server 500 errors within the container logs. **"GET /1 HTTP/1.1" 500 211 "https://DOMAIN.ca/serviceworker.js"**

I look further within the network console and found nothing useful.

I decide to look up within the issues. Found #7 Looked over it and followed some instructions thinking it would be a permission issue and did not come to a solution. 

Im am stuck at this point and would really like to move to keep all the inv/companies data If I have to export then import data onto a fresh install this is something I do not mind doing!

Any help would be appreciated :)
