### ISSUE TITLE
Unable to launch an app using localhost

### ISSUE THREAD

**Issue by nithrous** [akaunting/docker#98]
OS: Ubuntu 18.04.6 LTS

Hi, Just installed an akaunting using steps in manual. I did not made any changes in the environments except setting the port to 12600 in docker compose, so it looks like this:

```
version: '3.7'

services:

  akaunting:
    container_name: akaunting
    image: docker.io/akaunting/akaunting:latest
    build:
      context: .
    ports:
      - 12600:80
    volumes:
      - akaunting-data:/var/www/html
    restart: unless-stopped
    env_file:
      - env/run.env
    environment:
      - AKAUNTING_SETUP
    depends_on:
      - akaunting-db

  akaunting-db:
    container_name: akaunting-db
    image: mariadb
    volumes:
      - akaunting-db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - env/db.env

volumes:
  akaunting-data:
  akaunting-db:
```

Calling `curl localhost:12600` returns `Empty reply from server`

How to fix this?
